language: php
php:
  - 7.0.26
  - 7.1.12
  - 7.2.0
install:
  - phpenv config-rm xdebug.ini
  - pecl install ast
  - composer install
script:
  - bin/pahout src
  - vendor/bin/phpunit
  - vendor/bin/phan
